on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3.1.1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: execute py script
      run: |
        python scripts/drudge_rss.py
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Lyman Epp
        author_email: lyman@epptech.com
        message: 'Commit latest'
        add: 'drudge.*'
