'on':
  schedule:
    - cron: '*/15 * * * *'
  push:
    paths:
      - scripts/drudge_rss.py
      - github/workflows/drudge.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build Drudge Report RSS feed
        run: |
          python scripts/drudge_rss.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: GitHub Actions
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add:
            - work/drudge.json
            - docs/drudge.rss
